- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: |
    sed -i 's|#{Build.BuildId}#|{{ CIRCLE_WORKFLOW_ID }}|g' {{ ENVIRONMENT_NAME }}-deployment.yaml
    ./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yaml
  args:
    chdir: $HOME
